### ISSUE TITLE
analytics.min.js contains junk that doesn't belong there

### ISSUE THREAD

**Issue by amfred** [segmentio/analytics.js-core#103] opened 2018-11-07 18:36 UTC
We were investigating a performance problem on our page and noticed that the analytics.min.js file that's included on our pages has a bunch of metadata that doesn't belong in there.

It's potentially useful that the Github commit ID is included, for debugging purposes, but I really don't want to have all of your maintainers' email addresses loaded on my page.  That's a potential GDPR concern.

gitHead":"a2ad22ca8df361ac7439510fe468c1fa9bf5f3ab","homepage":"https://github.com/segmentio/analytics.js-core#readme","keywords":["analytics","analytics.js","segment","segment.io"],"license":"SEE LICENSE IN LICENSE","lint-staged":{"linters":{"*.{js,json,md}":["prettier-eslint --write","git add"]}},"main":"lib/index.js","maintainers":[{"name":"achille-roussel","email":"achille.roussel@gmail.com"},{"name":"alan-segment","email":"alan@segment.com"},{"name":"albert.segment","email":"albert@segment.com"},{"name":"amillet89","email":"alex@segment.io"},{"name":"andreiko_ru","email":"mail@andreiko.ru"},{"name":"anoonan","email":"amnoonann@gmail.com"},{"name":"atrivedi1","email":"akash@segment.com"},{"name":"bgamwell","email":"brennan@segment.com"},{"name":"boggsboggs","email":"john.boggs@segment.com"},{"name":"calvinfo","email":"calvin@calv.info"},{"name":"carlosmecha","email":"mecha.carlos@gmail.com"},{"name":"ccnixon","email":"chrisnxn@gmail.com"},{"name":"chenpengcheng","email":"pengcheng.chen@gmail.com"},{"name":"chrisbuttery","email":"info@chrisbuttery.com"},{"name":"colinking","email":"me@colinking.co"},{"name":"cyrusroshan","email":"hello@cyrusroshan.com"},{"name":"dfuentes","email":"daniel.richard.fuentes@gmail.com"},{"name":"dominicbarnes","email":"dominic@dbarnes.info"},{"name":"dscrobonia","email":"davidscrobonia@gmail.com"},{"name":"eesegment","email":"eric.ellett@segment.com"},{"name":"emilio-gomez-lavin","email":"emilio@segment.com"},{"name":"emily.luckette","email":"emily@segment.com"},{"name":"erickimsegment","email":"eric@segment.com"},{"name":"estela-diaz","email":"estela.diaz@segment.com"},{"name":"f2prateek","email":"f2prateek@gmail.com"},{"name":"fathyb","email":"fathy.boundjadj@gmail.com"},{"name":"fforres","email":"felipe.torressepulveda@gmail.com"},{"name":"flaque","email":"flaqueeau@gmail.com"},{"name":"gnijor","email":"nijor22@gmail.com"},{"name":"hanothan","email":"hankim813@gmail.com"},{"name":"ivolo","email":"ilya@segment.io"},{"name":"jamesmcguinness","email":"james.mcguinness@segment.com"},{"name":"jeroenransijn","email":"jssrdesign@gmail.com"},{"name":"jfabre-segment","email":"julien@segment.com"},{"name":"jfarah","email":"julio.farah@segment.com"},{"name":"jfmaggie","email":"jfmaggie@gmail.com"},{"name":"jlee9595","email":"justin@segment.com"},{"name":"joeybloggs","email":"dean@segment.com"},{"name":"josh_segment","email":"josh@segment.com"},{"name":"joshwget","email":"josh@curl.me"},{"name":"ladanazita","email":"ladanazita@gmail.com"},{"name":"lauramunozjimenez","email":"laura.munoz@segment.com"},{"name":"leifdreizler","email":"leifdreizler@gmail.com"},{"name":"mag"},{"name":"maxence-charriere","email":"charriere@outlook.com"},{"name":"monicadamborenea","email":"monica@segment.com"},{"name":"msanterre","email":"mooxeh@gmail.com"},{"name":"mshwery","email":"mshwery@gmail.com"},{"name":"n2parko","email":"kevin@segment.com"},{"name":"nettofarah","email":"nettofarah@gmail.com"},{"name":"notfelineit","email":"notfelineit@gmail.com"},{"name":"nucleartide","email":"jasontu4@gmail.com"},{"name":"nzoschke","email":"nzoschke@gmail.com"},{"name":"peripheral","email":"peter.h.richmond@gmail.com"},{"name":"rarchana2001asu","email":"archana@segment.com"},{"name":"rlc4","email":"rickyconnell@gmail.com"},{"name":"rowno","email":"rowno@webspirited.com"},{"name":"rpaul80","email":"rpaul80@gmail.com"},{"name":"sahilp","email":"sahil@segment.com"},{"name":"segment-admin","email":"tools+npm@segment.com"},{"name":"segment-anastassia","email":"anastassia@segment.com"},{"name":"segment-andy-yeo","email":"andy.yeo@segment.com"},{"name":"segment-cyammine","email":"chris.yammine@segment.com"},{"name":"segment-danielstjules","email":"danielst.jules@segment.com"},{"name":"segment-scott","email":"scott@segment.com"},{"name":"segment-ulysse","email":"ulysse@segment.com"},{"name":"segmentaimee","email":"aimee@segment.com"},{"name":"segmentio","email":"tools@segment.com"},{"name":"segmentmfischer","email":"michael.fischer@segment.com"},{"name":"sperand-io","email":"chris@sperand.io"},{"name":"srthurman","email":"srthurman@gmail.com"},{"name":"systemizer","email":"robmcqn@gmail.com"},{"name":"tamarrow","email":"tamarrow@gmail.com"},{"name":"tejasmanohar","email":"me@tejas.io"},{"name":"tyson_segment","email":"tyson@segment.com"},{"name":"vdemedes","email":"vdemedes@gmail.com"},{"name":"willallison","email":"will.allison@segment.com"},{"name":"williams-blake","email":"blake@segment.com"},{"name":"xagos","email":"xavier.agostini@mail.mcgill.ca"},{"name":"yields","email":"yields@icloud.com"}],

**Comment by f2prateek** [comment] 2018-11-08 04:19
I'm not 100% sure I understand the GDPR concern - this is a list of maintainers who have write access to this repo (which is comprised of employees at Segment), and it is publicly available via NPM. You could run `npm view @segment/analytics.js-core` to see it as well).

I do agree this is a bug, and something we have on our backlog to fix. However, I'm closing this issue as it's a duplicate of https://github.com/segmentio/analytics.js-core/issues/37. Please keep an eye on that issue for updates.

**Closed by f2prateek** 2018-11-08 04:19 UTC

**Comment by amfred** [comment] 2018-11-13 18:53
I'll watch that #37, thanks.

We're conservative about data privacy.  The problem is not that the data is publicly available; it's that I'm unintentionally republishing it on _my_ web pages.  I shouldn't unintentionally republish another company's employees' email addresses or be held responsible if someone asks to be removed from that list.  That said, I'm not a lawyer!
